version: "3.8"
services:
  webui:
    container_name: pf2sheet-webui
    build:
      context: ./apps/web-ui
      dockerfile: Dockerfile
    ports:
      - 80:8080
    depends_on:
      - backend
  backend:
    container_name: pf2sheet-backend
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - app_network
  postgres:
    container_name: pf2sheet-postgres
    image: postgres:15
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
