// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: add_player.sql

package dao

import (
	"context"
)

const addPlayer = `-- name: AddPlayer :exec
INSERT INTO "players"("display_name", "pass_hash", "login")
  VALUES($1, $2, $3) RETURNING ("id")
`

type AddPlayerParams struct {
	DisplayName string
	PassHash    string
	Login       string
}

func (q *Queries) AddPlayer(ctx context.Context, arg AddPlayerParams) error {
	_, err := q.db.Exec(ctx, addPlayer, arg.DisplayName, arg.PassHash, arg.Login)
	return err
}
