// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: add_session.sql

package dao

import (
	"context"
)

const addSession = `-- name: AddSession :exec
INSERT INTO "sessions"("token", "player_id")
  VALUES($1, $2)
`

type AddSessionParams struct {
	Token    string
	PlayerID int32
}

func (q *Queries) AddSession(ctx context.Context, arg AddSessionParams) error {
	_, err := q.db.Exec(ctx, addSession, arg.Token, arg.PlayerID)
	return err
}
