// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delete_session_by_token.sql

package dao

import (
	"context"
)

const deleteSessionByToken = `-- name: DeleteSessionByToken :exec
DELETE FROM "sessions" WHERE "token" = $1
`

func (q *Queries) DeleteSessionByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteSessionByToken, token)
	return err
}
