// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: find_player_by_login.sql

package dao

import (
	"context"
)

const findPlayerByLogin = `-- name: FindPlayerByLogin :one
SELECT players.id, players.display_name, players.pass_hash, players.login FROM "players" WHERE "login" = $1
`

type FindPlayerByLoginRow struct {
	Player Player
}

func (q *Queries) FindPlayerByLogin(ctx context.Context, login string) (*FindPlayerByLoginRow, error) {
	row := q.db.QueryRow(ctx, findPlayerByLogin, login)
	var i FindPlayerByLoginRow
	err := row.Scan(
		&i.Player.ID,
		&i.Player.DisplayName,
		&i.Player.PassHash,
		&i.Player.Login,
	)
	return &i, err
}
