// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: get_all_classes.sql

package dao

import (
	"context"
)

const getAllClasses = `-- name: GetAllClasses :many
SELECT classes.id, classes.code, classes.title FROM "classes"
`

type GetAllClassesRow struct {
	Class Class
}

func (q *Queries) GetAllClasses(ctx context.Context) ([]*GetAllClassesRow, error) {
	rows, err := q.db.Query(ctx, getAllClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetAllClassesRow
	for rows.Next() {
		var i GetAllClassesRow
		if err := rows.Scan(&i.Class.ID, &i.Class.Code, &i.Class.Title); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
