// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import ()

type Ancestry struct {
	ID    int32
	Code  string
	Title string
}

type Class struct {
	ID    int32
	Code  string
	Title string
}

type Player struct {
	ID          int32
	DisplayName string
	PassHash    string
	Login       string
}

type SchemaMigration struct {
	Version string
}

type Session struct {
	Token    string
	PlayerID int32
}

type Sheet struct {
	ID         int32
	PlayerID   int32
	AncestryID *int32
	ClassID    *int32
	Background *string
	Fullname   *string
	Level      *int16
	HpCurrent  *int16
	HpMax      *int16
}
