// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"context"
)

type Querier interface {
	GetAllAncestries(ctx context.Context) ([]*GetAllAncestriesRow, error)
	GetAllClasses(ctx context.Context) ([]*GetAllClassesRow, error)
	GetPlayerSheets(ctx context.Context, id int32) ([]*GetPlayerSheetsRow, error)
}

var _ Querier = (*Queries)(nil)
