// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package dao

import (
	"context"
)

type Querier interface {
	AddPlayer(ctx context.Context, arg AddPlayerParams) error
	AddSession(ctx context.Context, arg AddSessionParams) error
	DeleteSessionByToken(ctx context.Context, token string) error
	FindPlayerByLogin(ctx context.Context, login string) (*FindPlayerByLoginRow, error)
	FindSessionByPlayerID(ctx context.Context, playerID int32) (*FindSessionByPlayerIDRow, error)
	FindSessionByToken(ctx context.Context, token string) (*FindSessionByTokenRow, error)
	GetAllAncestries(ctx context.Context) ([]*GetAllAncestriesRow, error)
	GetAllClasses(ctx context.Context) ([]*GetAllClassesRow, error)
	GetPlayerSheets(ctx context.Context, id int32) ([]*GetPlayerSheetsRow, error)
}

var _ Querier = (*Queries)(nil)
